### ISSUE TITLE
KerbalStuff Down

### ISSUE THREAD

**Issue by lstanden** [DennyTX/DockingCam#2]
Any chance you can provide an alternate download link, as KerbalStuff is now offline?

Thanks

**Comment by DennyTX** [comment]
hi. yes. in days it will be in  http://spacedock.info/  

> Среда, 24 февраля 2016, 1:34 -08:00 от Lee Standen notifications@github.com:
> 
> Any chance you can provide an alternate download link, as KerbalStuff is now offline?
> Thanks
> —
> Reply to this email directly or  view it on GitHub .

---

Лебедев Д.А.

**Comment by Bradley-Blya** [comment]
But i whant it nooow!
(кажись на яндексе есть:)

**Comment by fr33soul** [comment]
no chance to download it?

**Comment by CalculusWarrior** [comment]
Will this mod be updated on SpaceDock soon?
